site_name: JAX-Triton
site_description: The documentation for JAX-Triton
site_author: Google

repo_url: https://github.com/jax-ml/jax-triton
repo_name: jax-ml/jax-triton

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: "material/vector-link"
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.sections
    - toc.integrate
    - header.autohide

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

plugins:
- mkdocstrings:
    handlers:
      python:
        import:
        - https://installer.readthedocs.io/en/stable/objects.inv

nav:
  - "index.md"
  - "triton_call.md"

strict: true
